# numpy

NumPy – Numerical Python – библиотека для работы с многомерными массивами.

<div align="center">
  <img src="images/NumPy_logo_2020.svg" width="400" title="NumPy"/>
</div>

- [Документация](https://numpy.org/doc/stable/)
- [API](https://numpy.org/doc/stable/reference/index.html)

In [1]:
import numpy as np
np.__version__

'1.23.5'

## Константы

Доступные [константы](https://numpy.org/devdocs/reference/constants.html).  
`numpy.newaxis` - удобный псевдоним для отсутствующей оси. Крайне полезен при индексировании массивов.

## N-мерный массив (ndarray)

### Создание

#### С помощью numpy.array(object, dtype=None, ...)

dtype можно посмотреть [здесь](https://numpy.org/devdocs/user/basics.types.html).

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.array([[1., 2, 3], [4, 5, 6]])
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


#### С помощью numpy.zeros(shape, dtype=float, order='C', *, like=None) - массив, заполненый нулями

In [7]:
x = np.zeros((5, 3), dtype=np.float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


C:\Users\UD\AppData\Local\Temp\ipykernel_11752\1307394261.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((5, 3), dtype=np.float)


In [8]:
x = np.zeros((5, 3), dtype=float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### С помощью numpy.ones(shape, dtype=None, order='C', *, like=None) - массив, заполненый единицами

In [ ]:
2 ** 8 - 1

In [13]:
x = np.ones((5, 3), dtype=np.uint8)
x[0, 0] = 258
print(x)

[[2 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


#### С помощью numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None) - единичная матрица

In [14]:
x = np.eye(5, 9, dtype=int)
print(x)

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


#### С помощью numpy.empty(shape, dtype=float, order='C', *, like=None) - массив, заполненый "мусором"

In [17]:
x = np.empty((5, 3), dtype=np.int16)
print(x)

[[    0     0     1]
 [    0     0     0]
 [  536     0  1276]
 [    0     0     0]
 [  768     0 32764]]


#### С помощью numpy.arange(start, stop, step) - создает массив, значения которого находятся в диапазоне от start до stop с шагом step

In [18]:
x = np.arange(0, 1, 0.12)
print(x)

[0.   0.12 0.24 0.36 0.48 0.6  0.72 0.84 0.96]


#### С помощью numpy.linspace(start, stop, num_of_elements) - создает массив с количеством элементов, равным num_of_elements, значения находятся в диапазоне от start до stop

In [19]:
x = np.linspace(0, 1.9, 20)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


#### С помощью numpy.logspace() - аналогично linspace, но значения элементов нахотятся в пределах логарифмической шкалы

In [20]:
x = np.logspace(0, 90, 10)
print(x)

[1.e+00 1.e+10 1.e+20 1.e+30 1.e+40 1.e+50 1.e+60 1.e+70 1.e+80 1.e+90]


### Обращение к элементам

In [21]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x.shape)
print(x)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
x[1]

array([[5, 6],
       [7, 8]])

In [23]:
x[-1]

array([[5, 6],
       [7, 8]])

In [24]:
x[0, 0]

array([1, 2])

In [25]:
x[0, 0, 0]

1

In [26]:
indexes = np.array([0, 1])
x[indexes]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
x[::-1]

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

In [28]:
x[::-1, ::-1]

array([[[7, 8],
        [5, 6]],

       [[3, 4],
        [1, 2]]])

In [29]:
x[::-1, ::-1, ::-1]

array([[[8, 7],
        [6, 5]],

       [[4, 3],
        [2, 1]]])

### Атрибуты
Полный список атрибутов [здесь](https://numpy.org/devdocs/reference/arrays.ndarray.html#array-attributes).

In [30]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### obj.ndim - количество измерений массива 

In [31]:
x.ndim

2

#### obj.shape - размеры массива

In [32]:
x.shape

(4, 3)

#### obj.size - общее количество элементов в массиве

In [33]:
x.size

12

#### obj.dtype - тип элементов в массиве

In [34]:
x.dtype

dtype('int32')

#### obj.itemsize - размер элемента

In [35]:
x.itemsize

4

#### obj.data - буфер с элементами массива

In [36]:
x.data

#### obj.flat - одномерный итератор по элементам массива

In [37]:
e = x.flat
e[[5, 6]]

array([6, 7])

In [38]:
x[1, 2]

6

In [39]:
for element in x.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


#### obj.T - транспонированный массив

In [40]:
x.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
x

#### obj.real - действительная часть

In [41]:
x.real

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### obj.imag - мнимая часть

In [42]:
x.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Методы управления формой

#### obj.reshape(shape[, order]) - возвращает массив с новой формой

In [43]:
a = np.linspace(1, 12, 12)
print(a)
b = a.reshape((3, 4))
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [44]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.reshape((3, 4))
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1  2  3 -4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.reshape((3, 4), order='C')
print(b)

In [45]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.reshape((3, 4), order='F')
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1 10  8  6]
 [-4  2 11  9]
 [77  5  3 12]]


In [46]:
b = a.reshape((3, 3))
print(b)

ValueError: cannot reshape array of size 12 into shape (3,3)

#### obj.resize(new_shape) - меняет массив в соответствии с новыми размером и формой

In [47]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
a.resize((3, 4))
print(a)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1  2  3 -4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [48]:
a.resize((4, 5))
print(a)

[[ 1  2  3 -4  5]
 [ 6 77  8  9 10]
 [11 12  0  0  0]
 [ 0  0  0  0  0]]


#### obj.transpose(*axes) - транспонирует массив

In [49]:
a = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(a)
b = a.transpose()
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]
[[ 1 -4 77 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [50]:
b = a.transpose(0, 1)
print(b)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


In [51]:
b = a.transpose(1, 0)
print(b)

[[ 1 -4 77 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


#### ndarray.swapaxes(axis1, axis2) - возвращает массив с помененными местами осями

In [52]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.swapaxes(0, 2)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [53]:
a[0, 0, 1] == b[1, 0, 0]

True

In [54]:
a[1, 1, 0] == b[0, 1, 1]

True

#### obj.flatten([order]) - возвращает одномерный массив всех элементов

In [55]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.flatten()
print(b)
print(type(b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [56]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.flatten(order='C')
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [57]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
b = a.flatten(order='F')
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 5 3 7 2 6 4 8]


### Вычислительные методы

Полный список методов [здесь](https://numpy.org/devdocs/reference/arrays.ndarray.html#array-methods).

In [58]:
x = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


#### obj.max() - значение максимального элемента

In [59]:
x.max()

77

In [60]:
x.max(0)

array([77, 11, 12])

In [61]:
x.max(1)

array([ 3,  6, 77, 12])

#### obj.argmax() - индекс максимального элемента

In [62]:
x.argmax()

6

#### obj.min() - значение минимального элемента

In [63]:
x.min()

-4

#### obj.argmin() - индекс минимального элемента

In [64]:
x.argmin()

3

#### obj.sum() - значение суммы элементов

In [65]:
x.sum()

140

#### obj.cumsum() - значение кумулятивной суммы

In [66]:
print(a)
x.cumsum()

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([  1,   3,   6,   2,   7,  13,  90,  98, 107, 117, 128, 140])

#### obj.mean() - среднее арифметическое

In [67]:
x.mean()

11.666666666666666

#### obj.var() - дисперсия

In [68]:
x.var()

408.05555555555543

#### obj.std() - стандартное отклонение

In [69]:
x.std()

20.200385034834248

#### obj.all() - True, если все элементы True

In [70]:
x

array([[ 1,  2,  3],
       [-4,  5,  6],
       [77,  8,  9],
       [10, 11, 12]])

In [71]:
x[0, 0] = 1
print(x)
x.all()

[[ 1  2  3]
 [-4  5  6]
 [77  8  9]
 [10 11 12]]


True

#### obj.any() - True, если один из элементов True

In [72]:
x.any()

True

### Прочие методы

#### obj.tolist() - Возвращает ndim-уровневый список списков

In [73]:
x = np.ones((2, 3, 4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [74]:
a = x.tolist()
print(a)
print(type(a))

[[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]], [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]]
<class 'list'>


#### obj.fill(value) - заполняет массив заданным значением

In [75]:
x.fill(5)
print(x)

[[[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]]


In [76]:
x = np.array([[1, 2, 3], [-4, 5, 6], [77, 8, 9], [10, 11, 12]])
y = np.ones((4, 3), dtype=int) * 5
x == y

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [77]:
np.all(x == y)

False

## Операции

Возможно применение любой арифметичесткой операции (+, -, *, /, //, %, divmod(), ** or pow(), <<, >>, &, ^, |, ~) и операций сравнения (==, <, >, <=, >=, !=) 

In [78]:
x = np.array([[3, 2, 1], [4, 5, 6]])
y = np.array([[9, 2, 7], [10, 11, 12]])

In [79]:
x + y

array([[12,  4,  8],
       [14, 16, 18]])

In [80]:
x + 3

array([[6, 5, 4],
       [7, 8, 9]])

In [81]:
x * y

array([[27,  4,  7],
       [40, 55, 72]])

In [82]:
x / y

array([[0.33333333, 1.        , 0.14285714],
       [0.4       , 0.45454545, 0.5       ]])

In [83]:
y // x

array([[3, 1, 7],
       [2, 2, 2]])

In [84]:
y % x

array([[0, 0, 0],
       [2, 1, 0]])

In [85]:
divmod(y, x)

(array([[3, 1, 7],
        [2, 2, 2]]),
 array([[0, 0, 0],
        [2, 1, 0]]))

In [86]:
np.any(y == x)

True

In [87]:
y >= x

array([[ True,  True,  True],
       [ True,  True,  True]])

In [88]:
y < x

array([[False, False, False],
       [False, False, False]])

Полученные значения можно сохранять

In [89]:
z = y ** x
print(z)

[[    729       4       7]
 [  10000  161051 2985984]]


## Функции numpy
Их настолько много, что проще посмотреть документацию

### Сортировка

In [90]:
a = np.array([[7, 2, 3], [3, 9, 6], [1, 8, 4]])
b = np.sort(a)
print(b)

[[2 3 7]
 [3 6 9]
 [1 4 8]]


In [91]:
a = np.array([[7, 2, 3], [3, 9, 6], [1, 8, 4]])
b = np.sort(a, axis=0)
print(b)

[[1 2 3]
 [3 8 4]
 [7 9 6]]


### Генерация вектора случайных чисел с равномерным распределением

In [92]:
x = np.random.uniform(0, 1, 200)
print(x.reshape(20, 10))

[[4.07328454e-01 4.23654952e-01 7.68029899e-01 9.20745988e-01
  2.13315126e-01 2.49662176e-01 2.72325072e-01 9.29053498e-01
  5.61131143e-01 1.82461807e-01]
 [4.81347703e-01 8.57740609e-02 9.35581683e-01 8.07415560e-01
  8.16577890e-01 8.97509227e-02 2.57643369e-01 6.48094701e-01
  8.15253766e-01 5.23141895e-01]
 [7.48350831e-02 5.55344403e-01 7.09121674e-01 2.77795288e-01
  3.65936296e-03 4.99900812e-01 4.39593782e-01 1.49207019e-01
  9.41910990e-01 6.19288202e-01]
 [2.30386493e-01 9.68774805e-01 5.44567466e-02 2.00188934e-01
  9.12803267e-01 2.90692821e-01 2.62442440e-02 7.96504305e-01
  1.25462041e-01 2.71391811e-01]
 [2.71717973e-01 9.07886293e-01 9.73302306e-01 2.35958113e-01
  2.60071171e-01 3.21473830e-01 7.03326861e-01 8.23521848e-01
  4.94658284e-01 3.02041334e-01]
 [4.76697470e-01 3.69205862e-01 1.16806211e-01 8.19214775e-01
  9.16985359e-01 7.35541281e-01 9.29959815e-01 6.12419595e-01
  1.96936191e-01 6.27029616e-01]
 [4.53982356e-01 4.96502716e-01 8.20058254e-02 1.59922975e

In [93]:
x = np.random.randint(1, 15, (3, 3))
print(x)

[[ 3 11 10]
 [13  9 14]
 [ 1  1 11]]


In [94]:
x = np.random.randn(30)
print(x)

[-0.01919712 -0.37494607 -2.1836671   0.48239368 -0.62718339 -0.12535104
  1.51546879  2.65505281  1.96240823 -1.63242867 -0.98878938 -0.41617228
  0.57441485 -0.91111963  0.21302983 -0.66996386  0.94972013  1.28658736
  1.72012102 -1.63262898 -1.1778419   1.27754705 -2.10992972  1.48589509
  0.54648389  0.66069459 -0.6095903   1.39172411  1.86901644 -0.67006833]


### Генерация вектора случайных чисел с нормальным распределением

In [95]:
x = np.random.normal(0, 1, 1000)
y = x * 3 + 5
#print(y)
print(y.mean(), y.std())

4.950678054973285 2.9978405050178347


### Генерация двумерного массива случайных чисел со стандартным нормальным распределением

In [96]:
x = np.random.randn(600, 2)
print(x)

[[ 2.03921352  1.25111981]
 [-0.08534504 -0.76497411]
 [ 1.23914264  0.84243917]
 ...
 [-0.79591324  0.28286494]
 [-0.81594348  0.33371216]
 [-0.53921747  1.02738777]]


In [ ]:
import matplotlib.pyplot as plt
plt.scatter(x[:, 0], x[:, 1])

### Объединение массивов

In [97]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 0], [1, 2]])
print(a, b, sep='\n')

[[1 2]
 [3 4]
 [5 6]]
[[7 8]
 [9 0]
 [1 2]]


In [98]:
np.hstack((a, b))

array([[1, 2, 7, 8],
       [3, 4, 9, 0],
       [5, 6, 1, 2]])

In [99]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0],
       [1, 2]])

In [100]:
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0],
       [1, 2]])

In [101]:
np.concatenate((a, b), axis = 1)

array([[1, 2, 7, 8],
       [3, 4, 9, 0],
       [5, 6, 1, 2]])

In [102]:
np.stack((a, b))

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 0],
        [1, 2]]])

### Перестановки и перемешивание

In [103]:
np.random.permutation(10)

array([5, 7, 8, 4, 6, 0, 3, 2, 1, 9])

In [104]:
a = np.array([1, 6, 2, 8])
b = np.random.permutation(a)
print(a)
print(b)

[1 6 2 8]
[6 1 2 8]


In [105]:
a = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])
b = np.random.permutation(a)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [4 5]
 [2 3]
 [6 7]
 [8 9]]


In [106]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 1 3 2 7 0 8 4 9]


In [107]:
a = np.arange(10).reshape(5, 2)
print(a)
np.random.shuffle(a)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[8 9]
 [6 7]
 [0 1]
 [4 5]
 [2 3]]


### Сериализация

In [108]:
import os
a = np.random.default_rng().normal(0, 1, size=(2,4)) * 10
a

array([[ -0.29834118, -11.0915361 ,   3.40023574,   0.77663905],
       [ -0.85510153,  11.67986991,   3.84448772, -25.73248872]])

In [109]:
np.save( os.getcwd() + '/a.npy', a )

In [110]:
b = np.load(os.getcwd() + '/a.npy')
b

array([[ -0.29834118, -11.0915361 ,   3.40023574,   0.77663905],
       [ -0.85510153,  11.67986991,   3.84448772, -25.73248872]])

In [111]:
np.savetxt(os.getcwd() + '/b.txt', b, delimiter=" ")
with open(os.getcwd() + '/b.txt', 'r') as f:
    print(f.read())

-2.983411776967583307e-01 -1.109153609657253448e+01 3.400235740907080473e+00 7.766390524803516993e-01
-8.551015319378170165e-01 1.167986990857230367e+01 3.844487723579327998e+00 -2.573248872470728443e+01



In [112]:
np.loadtxt(os.getcwd() + '/b.txt')

array([[ -0.29834118, -11.0915361 ,   3.40023574,   0.77663905],
       [ -0.85510153,  11.67986991,   3.84448772, -25.73248872]])

In [113]:
np.genfromtxt(os.getcwd() + '/b.txt', delimiter=' ')

array([[ -0.29834118, -11.0915361 ,   3.40023574,   0.77663905],
       [ -0.85510153,  11.67986991,   3.84448772, -25.73248872]])